In [1]:
# Basic liberaries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn imports
from sklearn.model_selection import train_test_split
# Ignore warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
encoded_data = pd.get_dummies(data, dtype='int',drop_first=True)
encoded_data.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

In [4]:
encoded_data.columns = encoded_data.columns.str.replace('_yes', '')
encoded_data.columns = encoded_data.columns.str.replace('furnishingstatus_','')
encoded_data.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,semi-furnished,unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

In [5]:
# Test train split

x = encoded_data.drop(['price'],axis=1)
y = encoded_data[['price']]

#train-test-split

x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=42)
print('x_train dimension:',x_train.shape)
print('x_test dimension:',x_test.shape)
print('y_train dimension:',y_train.shape)
print('y_test dimension:',y_test.shape)

x_train dimension: (381, 13)
x_test dimension: (164, 13)
y_train dimension: (381, 1)
y_test dimension: (164, 1)

In [6]:
penguin_data = sns.load_dataset('penguins')
penguin_data.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [7]:
penguin_data.dropna(inplace=True)

In [8]:
encoded_pdata = pd.get_dummies(penguin_data, dtype='int',drop_first=True)
encoded_pdata.head()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male
0,39.1,18.7,181.0,3750.0,0,0,0,1,1
1,39.5,17.4,186.0,3800.0,0,0,0,1,0
2,40.3,18.0,195.0,3250.0,0,0,0,1,0
4,36.7,19.3,193.0,3450.0,0,0,0,1,0
5,39.3,20.6,190.0,3650.0,0,0,0,1,1

In [9]:
encoded_pdata.head()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male
0,39.1,18.7,181.0,3750.0,0,0,0,1,1
1,39.5,17.4,186.0,3800.0,0,0,0,1,0
2,40.3,18.0,195.0,3250.0,0,0,0,1,0
4,36.7,19.3,193.0,3450.0,0,0,0,1,0
5,39.3,20.6,190.0,3650.0,0,0,0,1,1

In [10]:
x = encoded_pdata.drop(['body_mass_g'],axis=1)
y = encoded_pdata[['body_mass_g']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
print('x_train dimension:',x_train.shape)
print('x_test dimension:',x_test.shape)
print('y_train dimension:',y_train.shape)
print('y_test dimension:',y_test.shape)

x_train dimension: (233, 8)
x_test dimension: (100, 8)
y_train dimension: (233, 1)
y_test dimension: (100, 1)